// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token    string `json:"token"`
	Username string `json:"username"`
}

// ListProblemsResponse defines model for ListProblemsResponse.
type ListProblemsResponse struct {
	Problems []Problem `json:"problems"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Problem defines model for Problem.
type Problem struct {
	AnswerCode  *string `json:"answerCode,omitempty"`
	Description string  `json:"description"`
	Explanation *string `json:"explanation,omitempty"`
	Hint        *string `json:"hint,omitempty"`
	Id          int64   `json:"id"`
	Language    string  `json:"language"`
	Level       string  `json:"level"`
	Order       int32   `json:"order"`
	StarterCode *string `json:"starterCode,omitempty"`
	Title       string  `json:"title"`
}

// ProgressResponse defines model for ProgressResponse.
type ProgressResponse struct {
	ClearedProblemIds []int64 `json:"clearedProblemIds"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// SubmitRequest defines model for SubmitRequest.
type SubmitRequest struct {
	Code     string `json:"code"`
	Language string `json:"language"`
}

// SubmitResponse defines model for SubmitResponse.
type SubmitResponse struct {
	Passed      bool  `json:"passed"`
	PassedTests int32 `json:"passedTests"`
	TotalTests  int32 `json:"totalTests"`
}

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	CurrentPassword string  `json:"currentPassword"`
	NewPassword     *string `json:"newPassword,omitempty"`
	NewUsername     *string `json:"newUsername,omitempty"`
}

// ProblemsInterfaceListParams defines parameters for ProblemsInterfaceList.
type ProblemsInterfaceListParams struct {
	Language *string `form:"language,omitempty" json:"language,omitempty"`
}

// AccountInterfaceUpdateJSONRequestBody defines body for AccountInterfaceUpdate for application/json ContentType.
type AccountInterfaceUpdateJSONRequestBody = UpdateAccountRequest

// AuthInterfaceLoginJSONRequestBody defines body for AuthInterfaceLogin for application/json ContentType.
type AuthInterfaceLoginJSONRequestBody = LoginRequest

// AuthInterfaceSignupJSONRequestBody defines body for AuthInterfaceSignup for application/json ContentType.
type AuthInterfaceSignupJSONRequestBody = SignupRequest

// ProblemsInterfaceSubmitJSONRequestBody defines body for ProblemsInterfaceSubmit for application/json ContentType.
type ProblemsInterfaceSubmitJSONRequestBody = SubmitRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/account/update)
	AccountInterfaceUpdate(w http.ResponseWriter, r *http.Request)

	// (POST /api/auth/login)
	AuthInterfaceLogin(w http.ResponseWriter, r *http.Request)

	// (POST /api/auth/signup)
	AuthInterfaceSignup(w http.ResponseWriter, r *http.Request)

	// (GET /api/problems)
	ProblemsInterfaceList(w http.ResponseWriter, r *http.Request, params ProblemsInterfaceListParams)

	// (GET /api/problems/{id})
	ProblemsInterfaceGet(w http.ResponseWriter, r *http.Request, id int64)

	// (POST /api/problems/{id}/submit)
	ProblemsInterfaceSubmit(w http.ResponseWriter, r *http.Request, id int64)

	// (GET /api/progress)
	ProgressInterfaceGet(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /api/account/update)
func (_ Unimplemented) AccountInterfaceUpdate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/auth/login)
func (_ Unimplemented) AuthInterfaceLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/auth/signup)
func (_ Unimplemented) AuthInterfaceSignup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/problems)
func (_ Unimplemented) ProblemsInterfaceList(w http.ResponseWriter, r *http.Request, params ProblemsInterfaceListParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/problems/{id})
func (_ Unimplemented) ProblemsInterfaceGet(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/problems/{id}/submit)
func (_ Unimplemented) ProblemsInterfaceSubmit(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/progress)
func (_ Unimplemented) ProgressInterfaceGet(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AccountInterfaceUpdate operation middleware
func (siw *ServerInterfaceWrapper) AccountInterfaceUpdate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AccountInterfaceUpdate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthInterfaceLogin operation middleware
func (siw *ServerInterfaceWrapper) AuthInterfaceLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthInterfaceLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthInterfaceSignup operation middleware
func (siw *ServerInterfaceWrapper) AuthInterfaceSignup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthInterfaceSignup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProblemsInterfaceList operation middleware
func (siw *ServerInterfaceWrapper) ProblemsInterfaceList(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ProblemsInterfaceListParams

	// ------------- Optional query parameter "language" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "language", r.URL.Query(), &params.Language, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "language"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "language", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProblemsInterfaceList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProblemsInterfaceGet operation middleware
func (siw *ServerInterfaceWrapper) ProblemsInterfaceGet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProblemsInterfaceGet(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProblemsInterfaceSubmit operation middleware
func (siw *ServerInterfaceWrapper) ProblemsInterfaceSubmit(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProblemsInterfaceSubmit(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ProgressInterfaceGet operation middleware
func (siw *ServerInterfaceWrapper) ProgressInterfaceGet(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProgressInterfaceGet(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/account/update", wrapper.AccountInterfaceUpdate)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/login", wrapper.AuthInterfaceLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/signup", wrapper.AuthInterfaceSignup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/problems", wrapper.ProblemsInterfaceList)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/problems/{id}", wrapper.ProblemsInterfaceGet)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/problems/{id}/submit", wrapper.ProblemsInterfaceSubmit)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/progress", wrapper.ProgressInterfaceGet)
	})

	return r
}

type AccountInterfaceUpdateRequestObject struct {
	Body *AccountInterfaceUpdateJSONRequestBody
}

type AccountInterfaceUpdateResponseObject interface {
	VisitAccountInterfaceUpdateResponse(w http.ResponseWriter) error
}

type AccountInterfaceUpdate200JSONResponse AuthResponse

func (response AccountInterfaceUpdate200JSONResponse) VisitAccountInterfaceUpdateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AuthInterfaceLoginRequestObject struct {
	Body *AuthInterfaceLoginJSONRequestBody
}

type AuthInterfaceLoginResponseObject interface {
	VisitAuthInterfaceLoginResponse(w http.ResponseWriter) error
}

type AuthInterfaceLogin200JSONResponse AuthResponse

func (response AuthInterfaceLogin200JSONResponse) VisitAuthInterfaceLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type AuthInterfaceSignupRequestObject struct {
	Body *AuthInterfaceSignupJSONRequestBody
}

type AuthInterfaceSignupResponseObject interface {
	VisitAuthInterfaceSignupResponse(w http.ResponseWriter) error
}

type AuthInterfaceSignup200JSONResponse AuthResponse

func (response AuthInterfaceSignup200JSONResponse) VisitAuthInterfaceSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ProblemsInterfaceListRequestObject struct {
	Params ProblemsInterfaceListParams
}

type ProblemsInterfaceListResponseObject interface {
	VisitProblemsInterfaceListResponse(w http.ResponseWriter) error
}

type ProblemsInterfaceList200JSONResponse ListProblemsResponse

func (response ProblemsInterfaceList200JSONResponse) VisitProblemsInterfaceListResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ProblemsInterfaceGetRequestObject struct {
	Id int64 `json:"id"`
}

type ProblemsInterfaceGetResponseObject interface {
	VisitProblemsInterfaceGetResponse(w http.ResponseWriter) error
}

type ProblemsInterfaceGet200JSONResponse Problem

func (response ProblemsInterfaceGet200JSONResponse) VisitProblemsInterfaceGetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ProblemsInterfaceSubmitRequestObject struct {
	Id   int64 `json:"id"`
	Body *ProblemsInterfaceSubmitJSONRequestBody
}

type ProblemsInterfaceSubmitResponseObject interface {
	VisitProblemsInterfaceSubmitResponse(w http.ResponseWriter) error
}

type ProblemsInterfaceSubmit200JSONResponse SubmitResponse

func (response ProblemsInterfaceSubmit200JSONResponse) VisitProblemsInterfaceSubmitResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ProgressInterfaceGetRequestObject struct {
}

type ProgressInterfaceGetResponseObject interface {
	VisitProgressInterfaceGetResponse(w http.ResponseWriter) error
}

type ProgressInterfaceGet200JSONResponse ProgressResponse

func (response ProgressInterfaceGet200JSONResponse) VisitProgressInterfaceGetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/account/update)
	AccountInterfaceUpdate(ctx context.Context, request AccountInterfaceUpdateRequestObject) (AccountInterfaceUpdateResponseObject, error)

	// (POST /api/auth/login)
	AuthInterfaceLogin(ctx context.Context, request AuthInterfaceLoginRequestObject) (AuthInterfaceLoginResponseObject, error)

	// (POST /api/auth/signup)
	AuthInterfaceSignup(ctx context.Context, request AuthInterfaceSignupRequestObject) (AuthInterfaceSignupResponseObject, error)

	// (GET /api/problems)
	ProblemsInterfaceList(ctx context.Context, request ProblemsInterfaceListRequestObject) (ProblemsInterfaceListResponseObject, error)

	// (GET /api/problems/{id})
	ProblemsInterfaceGet(ctx context.Context, request ProblemsInterfaceGetRequestObject) (ProblemsInterfaceGetResponseObject, error)

	// (POST /api/problems/{id}/submit)
	ProblemsInterfaceSubmit(ctx context.Context, request ProblemsInterfaceSubmitRequestObject) (ProblemsInterfaceSubmitResponseObject, error)

	// (GET /api/progress)
	ProgressInterfaceGet(ctx context.Context, request ProgressInterfaceGetRequestObject) (ProgressInterfaceGetResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AccountInterfaceUpdate operation middleware
func (sh *strictHandler) AccountInterfaceUpdate(w http.ResponseWriter, r *http.Request) {
	var request AccountInterfaceUpdateRequestObject

	var body AccountInterfaceUpdateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AccountInterfaceUpdate(ctx, request.(AccountInterfaceUpdateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AccountInterfaceUpdate")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AccountInterfaceUpdateResponseObject); ok {
		if err := validResponse.VisitAccountInterfaceUpdateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthInterfaceLogin operation middleware
func (sh *strictHandler) AuthInterfaceLogin(w http.ResponseWriter, r *http.Request) {
	var request AuthInterfaceLoginRequestObject

	var body AuthInterfaceLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthInterfaceLogin(ctx, request.(AuthInterfaceLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthInterfaceLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthInterfaceLoginResponseObject); ok {
		if err := validResponse.VisitAuthInterfaceLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AuthInterfaceSignup operation middleware
func (sh *strictHandler) AuthInterfaceSignup(w http.ResponseWriter, r *http.Request) {
	var request AuthInterfaceSignupRequestObject

	var body AuthInterfaceSignupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AuthInterfaceSignup(ctx, request.(AuthInterfaceSignupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AuthInterfaceSignup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AuthInterfaceSignupResponseObject); ok {
		if err := validResponse.VisitAuthInterfaceSignupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProblemsInterfaceList operation middleware
func (sh *strictHandler) ProblemsInterfaceList(w http.ResponseWriter, r *http.Request, params ProblemsInterfaceListParams) {
	var request ProblemsInterfaceListRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ProblemsInterfaceList(ctx, request.(ProblemsInterfaceListRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProblemsInterfaceList")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ProblemsInterfaceListResponseObject); ok {
		if err := validResponse.VisitProblemsInterfaceListResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProblemsInterfaceGet operation middleware
func (sh *strictHandler) ProblemsInterfaceGet(w http.ResponseWriter, r *http.Request, id int64) {
	var request ProblemsInterfaceGetRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ProblemsInterfaceGet(ctx, request.(ProblemsInterfaceGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProblemsInterfaceGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ProblemsInterfaceGetResponseObject); ok {
		if err := validResponse.VisitProblemsInterfaceGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProblemsInterfaceSubmit operation middleware
func (sh *strictHandler) ProblemsInterfaceSubmit(w http.ResponseWriter, r *http.Request, id int64) {
	var request ProblemsInterfaceSubmitRequestObject

	request.Id = id

	var body ProblemsInterfaceSubmitJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ProblemsInterfaceSubmit(ctx, request.(ProblemsInterfaceSubmitRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProblemsInterfaceSubmit")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ProblemsInterfaceSubmitResponseObject); ok {
		if err := validResponse.VisitProblemsInterfaceSubmitResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ProgressInterfaceGet operation middleware
func (sh *strictHandler) ProgressInterfaceGet(w http.ResponseWriter, r *http.Request) {
	var request ProgressInterfaceGetRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ProgressInterfaceGet(ctx, request.(ProgressInterfaceGetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ProgressInterfaceGet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ProgressInterfaceGetResponseObject); ok {
		if err := validResponse.VisitProgressInterfaceGetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
